### ISSUE TITLE
Workflow status model

### ISSUE THREAD

**Issue by makovsv** [makovpv/Carzine#10]
Show order statuses to client.
Profuser can change status in admin panel. Client can see the status in his profile / order list

![Image](https://github.com/makovpv/Carzine/assets/38849646/746c608d-7063-49e3-a90a-a691023a37e4)

**Comment by makovsv** [comment]
Не могу протестировать, так как не хватает прав для пользователя. Выдай мне права

**Comment by makovpv** [comment]
> Не могу протестировать, так как не хватает прав для пользователя. Выдай мне права

пользователь sergei_m
